spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vote?characterEncoding=utf-8&useSSL=false


server:
  servlet:
    context-path: /api
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gmr.vote.model.entity