spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    url:


server:
  servlet:
    context-path: /api
  port: 8080



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gmr.vote.model.entity